#!/bin/bash

# Recipe Images Feature Setup Guide
# This script provides step-by-step instructions for completing the recipe images implementation

echo "=========================================="
echo "Recipe Images Implementation Setup"
echo "=========================================="
echo ""

echo "Step 1: Verify Unsplash API Key"
echo "--------------------------------"
echo "You need an Unsplash API key to enable recipe images."
echo "Visit: https://unsplash.com/oauth/applications"
echo ""
echo "If you don't have an account:"
echo "1. Sign up for Unsplash (free)"
echo "2. Create a new application"
echo "3. Copy the Access Key"
echo ""

echo "Step 2: Update .env.local"
echo "------------------------"
echo "Open .env.local and replace the placeholder:"
echo ""
echo "UNSPLASH_ACCESS_KEY=your_api_key_here"
echo ""
echo "Replace 'your_api_key_here' with your actual Unsplash API key"
echo ""

echo "Step 3: Restart Development Server"
echo "-----------------------------------"
echo "Run: pnpm dev"
echo ""
echo "The dev server needs to restart to load the new environment variable"
echo ""

echo "Step 4: Test the Feature"
echo "------------------------"
echo "1. Go to http://localhost:3000/ai-chef"
echo "2. Generate a new recipe with AI Chef"
echo "3. Verify the recipe displays with an image"
echo "4. Click 'Share' to copy the shareable link"
echo "5. Paste the link in a new tab to view the shared recipe"
echo ""

echo "Step 5: Test Social Media Preview"
echo "-----------------------------------"
echo "For development, test with:"
echo "  - Facebook Debugger: https://www.opengraph.xyz/"
echo "  - Twitter Card Validator: https://cards-dev.twitter.com/validator"
echo ""
echo "Paste your shared recipe URL to see how it appears on social media"
echo ""

echo "Step 6: Monitor API Usage"
echo "------------------------"
echo "Unsplash free tier: 50 requests/hour"
echo ""
echo "The service includes:"
echo "  ✓ 24-hour image caching (reduces API calls)"
echo "  ✓ Smart fallback chain (ensures images load)"
echo "  ✓ URL validation (prevents broken images)"
echo ""

echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "Next: Update your .env.local file with your Unsplash API key"
echo ""
